navikt/veilarbportefoljeflatefs

- src/enhetsportefolje/enhetsportefolje.less
**Hva?**
Søkefeltet for fødselsnummer og navn vises ikke på "Min oversikt". 
Før: 
Etter:
> fjern margin slik at border ikke forsvinner

- src/middleware/api.ts
- src/utils/url-utils.ts
**Hva?**
Dersom `brukV2` er satt som queryparameter i url blir `v2` lagt til i url'en slik at alle kall får mot api/v2 av veilarbportefolje. 
Eks: `/veilarbportefolje/api/v2/enhet/1337/portefolje`
**Hvorfor?**
Slik at vi kan enkelt kan teste ut Postgres databasen ved å legge til `brukV2` slik: 
_https://app-q1.dev.adeo.no/veilarbportefoljeflatefs/enhet?enhet=0106&seAlle=false&side=1&sorteringsfelt=ikke_satt&sorteringsrekkefolge=ikke_satt&brukV2=true_
> TC-291 legg til queryParam for bruk av veilarbportefolje api v2

- src/components/sidebar/sidebar.tsx
Bruk av `aria-live` slik at skjermleser leser opp endringer i tab-containeren selv om fokus er på en av tabene. 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
> legg til aria-live

- package-lock.json
- package.json
- src/topp-meny/topp-meny.tsx
Denne PRen bytter ut den nåværende endringsloggen med en Sanity-basert endringslogg.
Foreløpig er `userId` satt til "1" og backendUrl `localhost:8080`. Endringsloggen henter ut data fra et sanity testprosjekt som inneholder all dataen fra nåværende endringslogg.
Merk: PRen fjerner ikke noe av logikken knyttet til den gamle endringsloggen (ligger i `components/endringslogg` og `components/modal/tour-modal`).
> Integrer Sanity-basert endringslogg

- src/components/modal/arbeidsliste/arbeidsliste.less
En raskfiks så de som ikke har mulighet til å skrolle uten å klikke (utenfor datovelgeren) kan fortsette sitt gode arbeid! 🖱️
> FS-214375 flytt datovelger over datofeltet i arbeidslistemodalen

- src/components/toolbar/paginering/paginering-selector.ts
- src/components/toolbar/paginering/paginering.tsx
- src/components/toolbar/toolbar.tsx
- src/ducks/paginering.ts
**Hva?**
- Fikser bug der knappetekst "vis 200" blir feil dersom man navigerer mellom `enhetensoversikt` og `minoversikt`
> FS-216531 handter visning av seFlere i egen state for enhetensoversikt

- src/components/knapper/rediger-knapp.tsx
- src/components/modal/arbeidsliste/arbeidsliste-informasjonsmelding.tsx
- src/components/modal/arbeidsliste/rediger-arbeidsliste-form.tsx
- src/components/modal/mine-filter/feil-tiltak-modal.tsx
- src/components/modal/mine-filter/mine-filter-oppdater.tsx
- src/components/modal/varselmodal/bekreft-sletting-modal.tsx
- src/components/modal/veiledergruppe/valgt-veiledergruppe-liste.tsx
- src/components/modal/veiledergruppe/veiledergruppe-modal.tsx
- src/components/tabell/arbeidslistebutton.tsx
- src/components/til-toppen-knapp/til-toppen-knapp.tsx
- src/filtrering/filtrering-label-arbeidsliste.tsx
- src/filtrering/filtrering-label.css
- src/minoversikt/moteplan/moteplan.tsx
- Flyttet resten av ikonene til props
- La til ikon på lenke for å vise at det åpnes ny fane
- Justert litt på filteretikettene, midtstilt og lagt på litt padding som DS av en eller annen grunn fjerner ( `--navds-button-icon-adjustment: -4px;` )
> Småfiks: knappeikoner etter DSv1

- src/application.tsx
- src/components/informasjonsmeldinger/informasjonsmeldinger.css
- src/components/informasjonsmeldinger/informasjonsmeldinger.tsx
- src/components/informasjonsmeldinger/sesjon-statusmelding.tsx
- src/components/informasjonsmeldinger/systemmeldinger.tsx
- src/components/modal/sesjonNotifikasjon.css
- src/ducks/informasjonsmelding.ts
- src/ducks/utils.ts
- src/enhetsportefolje/enhet-side.tsx
- src/hooks/redux/use-informasjonsmelding.tsx
- src/hooks/use-brukeraktivitet-token-refresh.tsx
- src/middleware/api.ts
- src/minoversikt/minoversikt-side.tsx
- src/mocks/index.ts
- src/mocks/session.ts
- src/mocks/utils.ts
- src/model-interfaces.ts
- src/reducer.ts
- src/style.css
- src/veiledere/veiledere-side.tsx
I stedet for å automatisk redirecte brukeren til innloggingssiden når sesjonen er utløpt, så viser vi nå heller en statusmelding med lenke til innloggingssiden. Dersom brukeren derimot velger å overse meldingen og trykker utløser et nettverkskall (feks. trykker på et filter) så vil vi derimot redirecte til innloggingssiden siden brukeren i dette tilfellet eksplisitt har utført en handling.
Dette er først og fremst for å unngå å forvirre brukeren, da den forrige implementasjonen ville ha redirected brukeren ved første input-event (dvs. "mousemove") som potensielt er forvirrende samt at det heller ikke gir brukeren mulighet til å eventuelt lagre unna arbeidet sitt.
> TC-254 Vise melding ved utløpt sesjon

- .nais/obo-nais-dev.yaml
Ref. endring i default brukertilganger for AzureAD, som annonsert i #nais-announcements: https://nav-it.slack.com/archives/C01DE3M9YBV/p1674475818557619
> Gi alle AzureAD brukere tilgang i dev

- .nais/obo-nais-prod.yaml
Ref. endring i default brukertilganger for AzureAD, som annonsert i #nais-announcements: https://nav-it.slack.com/archives/C01DE3M9YBV/p1674475818557619
> TC-320 Gi alle AzureAD-brukere tilgang i prod

- cypress/e2e/diverse_spec.js
- src/components/sidebar/sidevelger.tsx
- src/components/toolbar/sok-veileder.tsx
- src/components/veileder-checkbox-liste/veileder-checkbox-liste.tsx
- src/ducks/filtrering.ts
- src/ducks/ui/listevisning.ts
- src/enhetsportefolje/enhet-side.tsx
- src/filtrering/filtrering-label-container.tsx
- src/filtrering/filtrering-mine-filter/drag-and-drop/drag-and-drop.tsx
- src/filtrering/filtrering-status/filtrering-status.tsx
- src/filtrering/filtrering-veileder-grupper/filtrering-veiledergrupper.tsx
- src/filtrering/filtrering-veileder-grupper/veiledergruppe-innhold.tsx
- src/filtrering/filtrering-veileder-grupper/veiledergruppe_rad.tsx
- src/hooks/portefolje/use-fetch-portefolje.tsx
- src/minoversikt/minoversikt-side.tsx
- src/veiledere/veiledere-side.tsx
Litt usikker på endringen, men går fra å "resette" ved hver render i use-fetch-portefolje.tsx til å heller endre kolonner når man endrer filteret.
Må testes godt før merging
> Beholde kolonnene ved re-render med mindre man endrer filter

- src/components/modal/arbeidsliste/arbeidsliste-modal-rediger.tsx
- src/components/modal/arbeidsliste/fjern-fra-arbeidsliste-form.tsx
- src/components/modal/arbeidsliste/legg-til-arbeidslisteform.tsx
- src/ducks/arbeidsliste.ts
- src/middleware/api.ts
- src/mocks/index.ts
Feilen oppstår fordi Spring Boot 3 ikke tillater trailing-slash by-default lengre. Det var noen slike i veilarbportefoljeflatefs som gikk "under radaren". Denne PR-en fikser de jeg fant.
I stedet for å rote inne i den gamle `httpArbeidsliste`-funksjonen så lager jeg heller nye funksjoner med semantiske navn for de ulike operasjonene (lagre, oppdatere, slette).
Renamer litt for å unngå navnekollisjon.
> Fikse 404 feil

- .github/workflows/deploy-dev-gcp.yaml
Av og til ønsker man å deploye en branch i dev for testing. Da hadde det vært nice å kunne slippe å vente på at tester man vet kjører skal kjøre først. Det vil kun være mulig å ignorere testene ved manuell run av workflow-en - ved å sette default til `false` så sikrer vi at testene alltid kjører i forbindelse med PR/merge.
> Legg til mulighet til å skippe tester når vi deployer manuelt til dev

- package-lock.json
- package.json
- src/amplitude/amplitude.ts
- src/amplitude/taxonomy-events.ts
- src/components/modal/arbeidsliste/arbeidsliste-informasjonsmelding.tsx
- src/components/modal/arbeidsliste/arbeidsliste-modal-rediger.tsx
- src/components/modal/arbeidsliste/fjern-fra-arbeidsliste-form.tsx
- src/components/modal/arbeidsliste/legg-til-arbeidslisteform.tsx
- src/index.tsx
- src/utils/url-utils.ts
Jeg har satt default tracking til false, det vil si at vi ikke automatisk får med pageViewed osv. Dersom det er sånne ting vi vil ha med tenker jeg vi kan sette opp det på sikt. Ved å ikke ha det så har vi i alle fall mer kontroll på hva som trackes. Av det vi sender nå er det kun origin som sendes av url (https://veilarbportefoljeflate.intern.dev.nav.no/) ikke paths osv. Og så er det kun ikke identifiserbare data vi spesifikt tracker ved handling. 
Eksempel på tracking:
> Sette opp Amplitude og målinger på arbeidslista

- src/amplitude/taxonomy-events.ts
- src/components/modal/tildel-veileder/tildel-veileder.tsx
- src/components/toolbar/toolbar-knapp.tsx
- src/components/toolbar/toolbar.css
- src/components/toolbar/toolbar.tsx
- src/ducks/portefolje.ts
- src/model-interfaces.ts
Hva var ønsket? At det skal komme en pop-up boks etter man har trykket på "velg" her: 
Som advarer mot at arbeidslista blir slettet dersom noen av brukerne som er valgt:
- er fra en annen enhet OG  har innhold i arbeidslista OG at veileder man vil tildele er ny for bruker
Funksjonaliteten er sånn: Når man trykker på Avbryt, vil man kun avbryte tildelingen til de som vil få sletta arb.lista, resten blir da tildelt. 
Flere forklaringer i PR
> Advarsel for sletting arbeidslista

- src/minoversikt/moteplan/moteplan.css
- src/minoversikt/moteplan/moteplan.tsx
- src/minoversikt/moteplan/motetabell.tsx
- src/mocks/data/portefolje.ts
Den pleidde hoppe rundt om kring når ein scrolla. No gjer den ikkje det meir.
Løysinga er litt quick-fix i at den byttar posisjonen på Popover frå "left-start" til "bottom". Når vi har oppdatert designsystemet til v5.6.5 eller nyare kan vi i staden bruke `flip={false}` til å hindre at boksen hoppar rundt om kring.
I tillegg til å låse posisjonen til møteplanen har eg justert storleiken på den. No tek den opp mellom 400px og 50% av skjermhøgda, slik at brukaren kan scrolle inne i møteplanen i staden for å scrolle heile innhaldet. Litt mindre rørsle på skjermen, forhåpentleg vis ei meir logisk brukaroppleving.
Trellokort for detaljar og eksempel: https://trello.com/c/maKZuyfc/557-m%C3%B8teplanen-oppf%C3%B8rer-seg-merkelig-n%C3%A5r-man-har-mange-m%C3%B8ter-og-skroller
Før: …
> Fiksar bug med møteplan

- src/hooks/use-redirect-on-mount.ts
- src/utils/utils.ts
Vi har en Dependabot alert på følgende linje:
```
return window.location.host.includes('navikt.github.io');
```
Dette er i og for seg ikke er så farlig siden den bare styrer oppførselen til `useRedirectOnMount`. Så jeg kunne bare dismisset alerten, men tenkte jeg ville kikke litt på det likevel.
Jeg ser ikke helt poenget med å ha denne sjekken i det hele tatt. Når vi har denne sjekken på så resulterer det i at dersom man bruker demoen, står på "Min oversikt" og så refresher så byttes det automatisk til "Enhetens oversikt" som er litt rart. Fjerner derfor sjekken slik at det oppfører seg likt som lokalt, samt at vi slipper å ha en sjekk som er avhengig av en URL på et gitt format.
> Fjern unødvendig if-else sjekk

- package-lock.json
- package.json
- src/components/sidebar/sidebar-tab.tsx
- src/components/sidebar/sidebar.css
- src/components/tabell/sortering-header-ikon.tsx
- src/components/tabell/sortering-header.tsx
- src/components/tabell/tabell.css
- src/components/til-toppen-knapp/til-toppen-knapp.css
- src/components/til-toppen-knapp/til-toppen-knapp.tsx
- src/filtrering/filtrering-mine-filter/drag-and-drop/drag-and-drop.css
- src/filtrering/filtrering-mine-filter/drag-and-drop/flytt-knapp-wrapper.tsx
- src/filtrering/filtrering-mine-filter/toggle-switch/toggle-switch.css
- src/index.tsx
- src/veiledere/veiledere-tabell.tsx
Denne PR-en er i all hovudsak bytting av pil-ikon frå @navikt-ds-icons til @navikt-aksel-icons, med andre ord "frå dei mellomgamle ikona til dei nyaste".
Lukk-knappen for filterpanelet er bytta ut med knapp + ikon frå det nyaste designsystemet. Avhengigheiter til `navikt-frontend-lukknapp` og tilhøyrande styling er fjerna.
Og er no litt mindre UU-uvennleg reint fargemessig. Den er også likare toggle-knappen i designsystemet no.
> Bytt ut pil-ikon frå @navikt-ds-icons med dei frå @navikt-aksel-icons

- src/components/fargekategori/FargekategoriFeilhandtering.tsx
- src/components/fargekategori/fargekategori-popover.tsx
- src/components/fargekategori/fargekategori-tabellrad-knapp.tsx
- src/components/toolbar/fargekategori-toolbar-knapp.tsx
- src/mocks/api/veilarbportefolje.ts
Tar gjerne en gjennomgang for å forklare dette 😅 
Men kommentar i `src/mocks/api/veilarbportefolje.ts` viser hvor mange muligheter man har fra backend mtp på responser. Måten man håndterer feilkall og ok-kall er litt forskjellig med tanke på om body-objektet fra backend sendes videre fra `doThenDispatch`-funksjonen som JSON eller string, noe som gjør det litt vanskelig når man skal lese body ved en eventuell feil.
> Feilhåndtering for fargekategorier

- cypress/e2e/arbeidsliste_spec.js
- cypress/e2e/arbeidslistestatus_spec.js
- cypress/e2e/filter_spec.js
- cypress/e2e/mine-filter_spec.js
- cypress/e2e/veiledergrupper_spec.js
- src/components/modal/mine-filter/feil-tiltak-modal.tsx
- src/components/modal/veiledergruppe/søk-veiledere-veiledergrupper.tsx
Cypress-testar køyrer async. Testar som baserar seg på at ting skal skje i ei bestemt rekkefølgje risikerar å feile litt no og då. Eit døme er når ein hentar ut ein verdi, lagrar den, og så ein annan stad går ut i frå at denne lagringa faktisk har skjedd. Vi har gjort det masse. (Cypress-dokumentasjonen trøystar oss med at dette er ein veldig vanleg feil.)
I denne PR-en byttar vi ut `let variabelnamn`-notasjonen med å nøste funksjonskall i `.then`-notasjon. Då får vi tilgang på verdiane der vi treng dei, utan at andre funksjonar kan risikere å manipulere dei i mellomtida.
For enno meir detaljar og døme sjå https://docs.cypress.io/guides/references/best-practices#Assigning-Return-Values
---
Vi har også teke i bruk aliasing av DOM-element. For detaljert forklaring sjå [Cypress sin …
> Byttar ut eit u-mønster i Cypress-testar der vi lagrar verdiar i variablar

- cypress/e2e/arbeidsliste_spec.js
- cypress/e2e/arbeidslistestatus_spec.js
Legg inn litt delay mellom testar for å unngå at laster-modal kjem i vegen for andre sjekkar.
> Fiks feilande cypress-test

- src/components/fnr-list.tsx
- src/components/modal-liste.css
- src/components/modal/arbeidsliste/arbeidsliste-modal.tsx
- src/components/modal/arbeidsliste/arbeidsliste.css
- src/components/modal/arbeidsliste/fjern-fra-arbeidsliste-modal.tsx
- src/components/modal/feilmelding-brukere-modal.tsx
- src/components/modal/feilmelding-brukere.css
- src/components/modal/feilmelding-tildeling-modal.tsx
- src/components/modal/filter-feil-modal.tsx
- src/components/modal/mine-filter/mine-filter-varsel-modal.tsx
- src/components/modal/modal-tildelinger-ok.tsx
- src/components/modal/server-feil-modal.tsx
- src/components/modal/varselmodal/bekreft-sletting-modal.tsx
- src/components/modal/varselmodal/varsel-modal.css
- src/components/modal/varselmodal/varselmodal.tsx
- src/components/modal/veiledergruppe/ulagrede-endringer-modal.tsx
- src/components/modal/veiledergruppe/veiledergruppe-modal.css
- src/components/modal/veiledergruppe/veiledergruppeendring-feilet-modal.tsx
Alle varselmodalane brukar no header frå designsystemet. Det betyr at dei har fått lukkeknapp igjen etter oppdateringa frå v4 til v5 av designsystemet.
Eg har også gått over stylinga på modalane og venstrejustert all tekst. Spesielt dei stadane ein hadde fleire linjer tekst vil dette forhåpentlegvis gje eit litt ryddigare uttrykk, sidan alt no ligg langs same marg.
> Bruk header frå designsystemet på varsel-modalar

- public/index.html
- src/mocks/api/modiacontextholder.ts
Det var noe kluss der vi forsøkte å hente internarbeidsflatedecorator-assets fra feil path (`https://navikt.github.io/internarbeidsflatedecorator/**` i stedet for `https://navikt.github.io/veilarbportefoljeflatefs/internarbeidsflatedecorator/**`).
Fikset dette ved å inkludere `%PUBLIC_URL%` i `index.html` hvor vi inkluderer filene.
Måtte også mocke ut `https://app.adeo.no/modiacontextholder/api/decorator`. Vet ikke helt hvorfor. Ser også at det er noen andre `https://app.adeo.no/*`-URLer som feiler i network tab-en, men disse var ikke nødvendig å mocke for å få demoen til å kjøre. Mulig det er noe logikk i [/public/internarbeidsflatedecorator](https://github.com/navikt/veilarbportefoljeflatefs/tree/master/public/internarbeidsflatedecorator) som forventer en miljøvariabel eller noe for å …
> Fiks feil hvor appen ikke ville laste pga. at vi ikke fant internarbeidsflatedecorator-assets

- cypress/e2e/filter_spec.js
- cypress/e2e/mine-filter_spec.js
- cypress/e2e/veiledergrupper_spec.js
- src/ducks/filtrering.ts
- src/filtrering/filtrering-label-container.tsx
Nokre brukarar har opplevd ein bug i Nullstill filter der knappen ikkje sletter alle filtervala. Ei hypotese hos oss er at dei kan ha bomma og sletta eit enkelt filterval i staden for å nullstille filtera. Dersom det var 3 valde filter vil dette fjerne Nullstill-knappen, som gjer det utydeleg for brukaren at det er fleire filter att.
Vårt fyrste forsøk på å løyse problemet blir difor å forenkle logikken til knappen litt, slik at den alltid er der når vi har filtrert på noko.
> Alltid vis "nullstill filtervalg" når det er filtrert på noko

- src/minoversikt/huskelapp/HuskelappIkonInngang.tsx
Dette gjer at ikonet vert brukt likt som i veilarbvisittkort.
Mål:
Skal ha ikon for huskelapp både når personen har huskelapp og når dei har arbeidsliste.
Frå før hadde dei "tomt ikon" når dei hadde arbeidsliste.
> Vis huskelappikon både når personen har huskelapp og arbeidsliste

- cypress/e2e/arbeidsliste_spec.js
- cypress/support/commands.js
- src/components/tabell/arbeidslisteikon.tsx
- src/components/toolbar/legg-til-arbeidsliste-knapp.tsx
- src/middleware/api.ts
- src/minoversikt/huskelapp/redigering/LagEllerEndreHuskelappModal.tsx
- src/minoversikt/huskelapp/redigering/lagreHuskelapp.ts
- src/minoversikt/huskelapp/redigering/slettEksisterendeArbeidsliste.ts
- src/minoversikt/minoversikt-bruker-panel.tsx
- src/mocks/data/portefolje.ts
Må ha to forskjellige kall mot endepunkt "slett arbeidsliste" så lenge vi fortsatt støtter arbeidslistefunksjon i oversikten. 
1. Slett arbeidsliste med tilhørende fargekategori (slett fra arbeidsliste modal)
2. Slett arbeidsliste uten å slette fargekategori (slett fra migreringsmodal: arbeidsliste til huskelapp) 
erstatter for #950
> Ikke slette fargekategori om du sletter arbeidsliste ved migrering til huskelapp

- src/components/toolbar/listevisning/listevisning-utils.ts
- src/ducks/ui/listevisning-selectors.ts
- src/ducks/ui/listevisning.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filtrering-filter.tsx
- src/filtrering/filtrering-label-container.tsx
- src/filtrering/filtrering-label.tsx
- src/konstanter.ts
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/mocks/data/portefolje.ts
- src/model-interfaces.ts
* Bytte ut alternativer for situasjon (de gamle vil komme inn under noen av de nye som f.eks "Mistet jobben", vil nå gå under "Jeg har blitt sagt opp av arbeidsgiver"
* Endre tittel på filter fra Svar fra registrering til Siste svar fra registrering og lagt til en "Sist endret dato"- kolonne slik at det enda tydligere kommer frem at bruker kan endre disse dataene.
> Populerer filter med data fra nytt arbeidssøkerregister

- src/components/fargekategori/bekreft-endre-fargekategori-pa-mange-modal.css
- src/components/fargekategori/bekreft-endre-fargekategori-pa-mange-modal.tsx
- src/components/fargekategori/fargekategori-ikon-mapper.tsx
- src/components/fargekategori/fargekategori-popover.tsx
- src/components/fargekategori/fargekategori-tabellrad-knapp.tsx
- src/components/toolbar/fargekategori-toolbar-knapp.tsx
- src/minoversikt/huskelapp/modalvisning/SlettHuskelappKnapp.tsx
https://trello.com/c/k11vkb8h/623-advarsel-n%C3%A5r-ein-endrar-meir-enn-10-fargekategoriar-samstundes
Visar ein modal når brukaren har > 10 valgte brukarar dei prøver endre farge på. Skal ikkje lukke popover medan modalen er vist, slik at eventuelle feilmeldinger dukker opp i popover.
> Legg til ein modal for å bekrefte handling når ein endrar kategori på mange personar

- src/components/fargekategori/FargekategoriFeilhandtering.tsx
Før viste vi ei liste over personar som feila uavhengig av om det var éin eller mange personar oppdateringa feila for. No viser vi ikkje lista om berre ei oppdatering feila.
> Ikkje vis liste av brukarar som feila når det berre var éin

- src/components/toolbar/fargekategori-toolbar-knapp.tsx
- src/minoversikt/huskelapp/huskelapp-wrapper/huskelapp-postitstyling.css
- src/minoversikt/huskelapp/modalvisning/HuskelappForModal.tsx
- src/minoversikt/huskelapp/panelvisning/HuskelappForPanel.tsx
- src/mocks/data/portefolje.ts
Gjør det lettere å lese og strukturere informasjonen. [Trello-kort](https://trello.com/c/3rJAGBW4)
\+ endre navn på fargekategori-knappen i toolbar til "endre kategori"
> Rendre whitespace i huskelapp-visning, bryt lange ord

- src/minoversikt/huskelapp/HuskelappIkonInngang.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/mocks/data/portefolje.ts
- src/model-interfaces.ts
Fjerner eventuelle linjeskift før huskelappteksten og viser kun tekst fram til første linjeskift, eller maks 30 tegn, i huskelapp-kolonnen
> Vis kun tekst før første linjeskift som overskrift i huskelappkolonne

- src/components/aksjon-knapp-med-popover-feilmelding/aksjon-knapp-med-popover-feilmelding.tsx
- src/enhetsportefolje/enhet-brukerpanel.tsx
La XY scroll position av valgte person fra liste til localstorage slik at den kan hentes tilbake fra localstorage når veileder nevigerer seg tilbake til portefolje fra personflate. Denne XY scroll posisjon skal brukes til å skrolle automatisk til valgte personen.
> La xy scroll position til localstorage

- src/minoversikt/huskelapp/redigering/HuskelappModal.tsx
- src/minoversikt/huskelapp/redigering/rediger-huskelapp.css
Gjer heile datovelgar synleg i redigeringsmodal, også når den flyt ut over grensene til forelderen.
> Gjer huskelappmodal litt finare å sjå på

- src/components/toolbar/listevisning/listevisning.css
- src/components/toolbar/listevisning/listevisning.tsx
- src/components/toolbar/toolbar.css
- src/components/toolbar/toolbar.tsx
- src/components/toolbar/velg-kolonner.tsx
Ryddigare og meir oversiktleg kode å jobbe vidare med. Unngå ubrukte props som gjer komponentane tyngre å lese.
Tek bort props dersom:
- Dei ikkje vert brukt i komponenten
- Dei aldri vert brukt der komponenten vert rendra
Fjernar også styling for klassenamn som ikkje vart sendt vidare frå props
Før:
Listevisning rendra VelgKolonner som igjen rendra sjølve listevisninga av kolonnevalg.
No:
VelgKolonner rendrer Listevisning og kolonnevalga.
> Destrukturer props og rydd i kolonnevalg

- .nais/obo-nais-dev.yaml
- .nais/obo-nais-prod.yaml
Modiacontextholder er migrert til gcp. Fss varianten fungerer kun midlertidig for å støtte i migrasjon.
> Bytt til å bruke contextholder i gcp

- src/components/tabell/brukernavn.tsx
- src/components/tabell/kolonner/tiltakshendelse-lenke-kolonne.tsx
- src/enhetsportefolje/brukerliste.css
- src/enhetsportefolje/enhet-kolonner.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- Ta bort padding på tiltakshendelse-lenke.
- Bruk same klasse til andre knappar i brukarliste som skal vere utan padding.
- Flytt "utan padding"-klassenamn inn i komponent i staden for å sende den med via props.
> Gjer styling av tiltakshendelse-lenke litt betre

- cypress/support/commands.js
- src/components/tabell/headerceller/BarnUnder18Ar.tsx
- src/components/tabell/headerceller/Bosted.tsx
- src/components/tabell/headerceller/BostedBydel.tsx
- src/components/tabell/headerceller/BostedDetaljer.tsx
- src/components/tabell/headerceller/BostedKommune.tsx
- src/components/tabell/headerceller/BostedSistOppdatert.tsx
- src/components/tabell/headerceller/Fnr.tsx
- src/components/tabell/headerceller/Fodeland.tsx
- src/components/tabell/headerceller/HeadercelleProps.ts
- src/components/tabell/headerceller/HuskelappFrist.tsx
- src/components/tabell/headerceller/HuskelappKommentar.tsx
- src/components/tabell/headerceller/Navn.tsx
- src/components/tabell/headerceller/OppfolgingStartet.tsx
- src/components/tabell/headerceller/Statsborgerskap.tsx
- src/components/tabell/headerceller/StatsborgerskapGyldigFra.tsx
- src/components/tabell/headerceller/Status14AVedtak.tsx
- src/components/tabell/headerceller/SvarfristCv.tsx
- src/components/tabell/headerceller/Tolkebehov.tsx
- src/components/tabell/headerceller/TolkebehovSistOppdatert.tsx
- src/components/tabell/headerceller/Tolkesprak.tsx
- src/components/tabell/headerceller/UtdanningOgSituasjonSistEndret.tsx
- src/components/toolbar/listevisning/listevisning-utils.ts
- src/ducks/ui/listevisning-selectors.ts
- src/ducks/ui/listevisning.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/model-interfaces.ts
Mål:
- Mindre duplikat i koden og kortare listehode-filer som er lettare å lese. Legg til rette for meir gjenbruk og rydding på sikt.
- Betre hjelpetekstar på kolonne-titlar
Kva er gjort:
- Listehode-filene for Enhetsoversikt og Min oversikt har fått alle kolonner-props sortert i same rekkefølge, slik at det er lettare å sjå kvar dei har overlapp (ctrl+f = <3)
- Kolonner som er like i både enhet og minoversikt er trukke ut i eigne komponentar.
- Endra namn på kolonne- og sorteringsenumar slik at same verdi har same namn i begge. 
- Gjennomgang av tekst og hjelpetekst på dei "nye" komponentane (i lag med Kari)
Kva er ikkje gjort:
- Kolonner som treng valgtefilter for å bestemme om dei skal visast
> Lag småkomponentar for header-celler

- src/style.css
Bakgrunn:
Vi har overskrive tekststorleiken i ein del designsystem-element til å bruke 0.875rem (14px) i oversikten. 
Løysing:
Vi skriv over overskrivinga slik at dekoratøren "ignorerer" !important-stylinga som vert brukt i resten av Oversikten.
Kommentar:
Vi vert ikkje heilt like med dette fyrste steget, men det er nærare enn vi var. Framgang heller enn perfeksjon.
Problemet som ikkje er løyst: knapp og heading får litt for lita skrift no, skulle vore 18px. Prøv om vi kan gjere noko utan å måtte bruke !important.
> Gjer at dekoratøren får lik(are) tekststorleik som på andre sider

- src/decorator.tsx
- src/utils/types/decorator-props-v3.ts
Ved å sende inn prop'en `fnrSyncMode="readOnly"`. Dette tilsvarer "ignoreWSEvents" (websocket-events) i dekoratøren v3 og gjer at oversiktfaner ignorerer alle oppdateringar av brukar-i-kontekst som dei ikkje er skuld i sjølv.
Burde løyse ctrl+klikk-buggen og problem der oversikten-sider navigerer til personsider fordi ein har søkt i anna fane.
> Unngår at dekoratøren les endringar i fnr frå kontekstholdaren

- src/components/toolbar/listevisning/listevisning-utils.ts
- Brukar begrepet "hendelse på tiltak" i staden for "tiltakshendelse", fordi det er det veiledarane ser andre stadar.
- Presiserar at oppdateringskolonna har ein dato slik at det vert lettare for veiledar å kople kva kolonne det er snakk om.
> Oppdater tekst for tiltakshendelse-kolonner i velg kolonner

- src/components/modal/mine-filter/mine-filter-nytt.tsx
- src/components/modal/mine-filter/mine-filter-oppdater.tsx
- src/minoversikt/mine-filter-lagre-filter-knapp.tsx
- src/style.css
Oppgåve frå Kari si skisse av "småfiks i oversikten".
Legg til stjerne-ikon på lagre-filter-knapp slik at det er litt tydelegare samanheng mellom "lagre filter" og "mine filter".
Tek også i bruk secondary-neutral i staden for secondary, fordi den blå-kanta knappen stakk seg litt ut blant alle dei grå.
> Legg til stjerne-ikon på lagre-filter-knapp

- src/components/modal/tildel-veileder/tildel-veileder-utils.ts
- src/components/modal/tildel-veileder/tildel-veileder.tsx
- src/components/modal/tildel-veileder/tildelveileder.test.ts
- src/components/toolbar/toolbar-knapp.tsx
- src/components/toolbar/toolbar.tsx
Denne PR-en er resultat av at eg refaktorerte noko logikk for å forstå den betre, oppdaga ein feil, laga test for feilen og retta den. Og rydda litt vidare i koden så den er lettare å forstå.
Med andre ord: den er for det meste eit mellomsteg i "skjul arbeidsliste"-reisa.
Eg har også skjult knappen for å opprette/fjerne arbeidsliste for mange brukarar i oversikten. (Denne er vanlegvis skjult av huskelapp-feature-brytaren, og er gjort mest for å vere konsekvente.)
> Refaktorer og fiks logikk i tildeling av ny veileder

- src/components/modal/tildel-veileder/tildel-veileder.tsx
Ved å ta bort dobbel lambda-funksjon (`() => () => {}`) slik at tildeling faktisk vert kalla
> Fiks bug i tildel veileder

- cypress/e2e/diverse_spec.js
- src/components/tabell/header.tsx
- src/components/tabell/headerceller/BarnUnder18Ar.tsx
- src/components/tabell/headerceller/Bosted.tsx
- src/components/tabell/headerceller/BostedDetaljer.tsx
- src/components/tabell/headerceller/BostedSistOppdatert.tsx
- src/components/tabell/headerceller/Fnr.tsx
- src/components/tabell/headerceller/Fodeland.tsx
- src/components/tabell/headerceller/HuskelappFrist.tsx
- src/components/tabell/headerceller/HuskelappKommentar.tsx
- src/components/tabell/headerceller/Navn.tsx
- src/components/tabell/headerceller/OppfolgingStartet.tsx
- src/components/tabell/headerceller/Statsborgerskap.tsx
- src/components/tabell/headerceller/StatsborgerskapGyldigFra.tsx
- src/components/tabell/headerceller/Status14AVedtak.tsx
- src/components/tabell/headerceller/SvarfristCv.tsx
- src/components/tabell/headerceller/Tolkebehov.tsx
- src/components/tabell/headerceller/TolkebehovSistOppdatert.tsx
- src/components/tabell/headerceller/Tolkesprak.tsx
- src/components/tabell/headerceller/UtdanningOgSituasjonSistEndret.tsx
- src/components/tabell/sortering-header.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-listehode.tsx
- Fjern ubrukt klassenamn
- Presiser i propnamn at header-id er brukt til test-id
- Ikkje generer (ubrukte) klassenamn med header-id
- Send inn fullstendige test-id-ar i staden for å generere dei med prefiks+id
- Bruk meir skildrande test-id for Om barnet-kolonne
> Rydd i header-testid

- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filtrering-filter.tsx
- src/filtrering/filtrering-label-container.tsx
- src/filtrering/filtrering-status/arbeidsliste.tsx
- src/filtrering/filtrering-status/fargekategori.tsx
- src/filtrering/filtrering-status/filtrering-status.tsx
- src/model-interfaces.ts
Skriv oss bort frå eit objekt som wrappa opensearch-filter-konstantane. 
Mål: 
- om vi uansett skal hardkode ting kan vi liksågodt gjere det direkte, ikkje via ein mapper
- gjere det lettare å finne ut kvar ulike opensearch-filterverdiar var i bruk. I IntelliJ kunne ein ikkje finne all bruk av nøkkelen i eit objekt, men ein kan det om konstanten vert brukt direkte.
Bonus:
No kan vi sjå at enkelte av konstantane for opensearch-filter ikkje er i bruk. Desse kan ryddast opp i på sikt.
> Rydd i filter-koden slik at den vert lettare å lese

- src/components/tabell/headerceller/Bosted.tsx
- src/components/tabell/kolonner/tekstkolonne.tsx
- src/enhetsportefolje/enhet-kolonner.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/utils/dato-utils.ts
- src/utils/utils.ts
Eit forsøk på å minske sannsynlegheita for at vi manglar celler i "tabellen" i oversikten, fordi dei ikkje har tekst å vise.
Vi har sett feil i dev før der det tilsynelatande vert returnert `null` i staden for å returnere ei tom celle når cella ikkje får inputtekst.
Kva er gjort:
Det er no obligatorisk å sende inn ein streng i tekst-celler. Strengen kan vere data, eller `"-"` dersom det ikkje er noko tekst å vise.
> Fiks kolonner utan innhald

- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-status/fargekategori.tsx
Frå kommentar på PR (som vi ikkje fekk med oss før vi merga): https://github.com/navikt/veilarbportefoljeflatefs/pull/1128
> Fiks rekkefølgja på fargekategori-filter

- src/model-interfaces.ts
Vi lagar filter så sjeldan at dette er lett å gløyme. Difor legg vi inn ei påminning i koden om at vi må halde filtermodellane i dei to repoa synkronisert,
> Legg til info om at veilarbfilter må oppdaterast ved filterendringar

- src/components/toolbar/velg-kolonner/velg-kolonner-config.ts
Tek gjerne innspel på tekstane som vert vist i velg-kolonne-menyen. Ser på desse som eit fyrsteutkast som kan justerast når Kari er attende.
> Gjer at ein kan velje kva for nokre 14a-kolonner som skal visast

- src/minoversikt/moteplan/motetabell.tsx
Har kommet inn en jirasak på at veiledere trenger årstall inn i møtepln for å holde oversikt over møteplan
> Legge til årstall på dato i møteplan

- src/filtrering/filtrering-filter/filtrering-filter.tsx
- Legg gamle innsatsgruppe-, hovedmål- og avvikfilter "utanfor" feature-toggle slik at dei berre er synlege når den er av.
- Legg til ein ny versjon av avvik-filteret (oppdatert tekst) i same filterbolk som dei nye filtera. Denne skal berre vere synleg når toggle er på.
> Skjul gamle § 14 a-filter når dei nye er skrudd på

- src/ducks/ui/listevisning-selectors.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
Slik at veileder slepp velje kolonna for å sjå informasjonen når dei kombinerer samanlikningsfilteret med eit av gjeldande vedtak-filtera.
> Vis samanlikne 14a-vedtak-kolonna før kolonner for gjeldande § 14 a-vedtak

- src/konstanter.ts
Til å bestemme om filter skal visast for $ 14 a-ting.
Då slepp vi skru på to ulike feature-togglar ved lansering.
For meir om denne vurderinga, sjå trellokort: https://trello.com/c/OWeW5rEq/831-bruk-same-featuretoggle-i-oversikten-visittkort-for-%C3%A5-vise-data-fr%C3%A5-eiga-kjelde
> Bruk same feature-toggle for §14a som veilarbdetaljerfs

- src/components/tabell/headerceller/AvtaltAktivitet.tsx
- src/components/tabell/headerceller/EnsligeForsorgereAktivitetsplikt.tsx
- src/components/tabell/headerceller/EnsligeForsorgereOmBarnet.tsx
- src/components/tabell/headerceller/EnsligeForsorgereUtlopOvergangsstonad.tsx
- src/components/tabell/headerceller/EnsligeForsorgereVedtaksperiode.tsx
- src/components/tabell/headerceller/MoteVarighet.tsx
- src/components/tabell/headerceller/MoterIDag.tsx
- src/components/tabell/headerceller/Motestatus.tsx
- src/components/tabell/headerceller/SisteEndring.tsx
- src/components/tabell/headerceller/SisteEndringDato.tsx
- src/components/tabell/headerceller/Status14AVedtak.tsx
- src/components/tabell/headerceller/TiltakshendelseDatoOpprettet.tsx
- src/components/tabell/headerceller/TiltakshendelseLenke.tsx
- src/components/tabell/headerceller/UnderVurderingAnsvarligVeileder.tsx
- src/components/tabell/headerceller/UnderVurderingVedtaksstatus.tsx
- src/components/tabell/headerceller/UnderVurderingVedtaksstatusEndret.tsx
- src/components/tabell/headerceller/UtlopteAktiviteter.tsx
- src/components/tabell/headerceller/VenterPaSvarFraBruker.tsx
- src/components/tabell/headerceller/VenterPaSvarFraNav.tsx
- src/components/tabell/headerceller/enhetens-oversikt/VeilederNavident.tsx
- src/components/tabell/headerceller/enhetens-oversikt/VeilederNavn.tsx
- src/components/tabell/headerceller/min-oversikt/Fargekategori.tsx
- src/components/tabell/headerceller/min-oversikt/Huskelapp.tsx
- src/components/toolbar/velg-kolonner/velg-kolonner-config.ts
- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
Målet her er å lage gjenbrukbare komponentar i staden for å hardkode verdiar for kolonneoverskrifter i to filer.
I tillegg vert "listehode"-filene lettare å få oversikt i når dei ikkje har like mykje detaljar.
Eg oppdaga nokre skilnadar mellom kolonner i Min oversikt og Enhetens oversikt:
- Ulik kolonnebreidd på "Om barnet"-kolonne
- Ulik tekst i "Under vurdering"-kolonner
Retting av desse har eigne commitar.
- At komponentnamn samsvarar med kolonne/sorteringsfelt
- At rekkefølgja på kolonner før/etter er lik i begge oversiktene
- At eg har kopiert over rett felt då eg oppretta komponentane
> Lag gjenbrukbare komponentar for fleire kolonneoverskrifter

- src/filtrering/filter-konstanter.ts
Gjer at vi har ulike tekstar for filtertags for Hovedmål frå Arena og ny løysing.
> Legg til meir detaljerte tekstar for hovedmål i filtertags

- package-lock.json
- package.json
- public/mockServiceWorker.js
Oppdaterer avhengigheiter som har `path-to-regexp` eller `cross-spawn` som underavhengigheit, fordi vi har sikkerheitsvarsel på desse underbiblioteka.
React-router er også omfatta av dette, men sidan den skal oppdaterast til ny hovudversjon (major version) tek eg det i ein eigen PR.
> Oppdater avhengigheiter

- src/components/sidebar/fanevelger.tsx
- src/components/sidebar/mine-filter-tab.tsx
- src/components/sidebar/sidebar-tab.tsx
Lukking av sidepanel fjerner ikkje Mine filter som valgt fane. Dette gjorde at ein ikkje kunne opne Mine faner etter å ha lukka den, utan å først velje ei anna fane.
https://trello.com/c/MBOqVHvC/866-fiks-bug-i-lukking-av-sidepanel-fr%C3%A5-mine-filter
Før:
https://github.com/user-attachments/assets/4765d5fa-b91b-4c5e-918b-125fbb5d6725
Etter:
https://github.com/user-attachments/assets/9faa8503-b4f4-4960-8844-0a890256e4b3
> Fiks lukkeknapp for sidepanel frå Mine filter

- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
Ta bort feature-toggle rundt Gjeldende-vedtak-kolonner slik at det er "valgt kolonne"-logikken som styrer om dei vert vist. Dette gjer at ein kan sjå relevante kolonner om ein bruker eit Mine filter som har blitt migrert til nye filterverdiar. 
Det er kun når eit gjeldande-vedtakfilter er valgt at ein kan sjå kolonnene, og den einaste måten å gjere det på er gjennom migrerte Mine filter.
Sjølve filtera er framleis bak toggle og vert ikkje synlege før vi lanserer. 
Dette er naudsynt når vi migrerer gamle hovedmål-/innsatsgruppefilter til tilsvarande filter for § 14 a.
> Ta bort feature-toggle rundt Gjeldende-vedtak-kolonner

- src/filtrering/filtrering-filter/filterform/barn-under-18-filterform.tsx
Tidlegare kunne det settast som default-verdi, men ikkje skrivast inn av brukaren. Vi trur det blir mindre forvirrande om det er love å skrive inn 18 også.
Resultata vil uansett ikkje vise 18-åringar, sidan dei ikkje er under 18 år.
Trello-kort: https://trello.com/c/GIMhFkAL/923-minibug-kan-ikkje-velje-18-i-barnunder18-men-det-kan-setjast-som-default-verdi-likevel
> Gjer at ein kan skrive inn 18 i "til-feltet" på filter

- package-lock.json
- package.json
- src/components/endringslogg/endringslogg.css
- src/components/endringslogg/tour-modal/tour-modal.tsx
- src/components/fargekategori/bekreft-endre-fargekategori-pa-mange-modal.tsx
- src/components/modal/egenModal.tsx
- src/components/modal/lastermodal/laster-modal.tsx
- src/components/modal/tildel-veileder/tildel-veileder.tsx
- src/components/modal/varselmodal/varselmodal.tsx
- src/components/modal/veiledergruppe/valgt-veiledergruppe-liste.tsx
- src/components/modal/veiledergruppe/veiledergruppe-modal.tsx
- src/components/til-toppen-knapp/til-toppen-knapp.css
- src/minoversikt/huskelapp/redigering/HuskelappModal.tsx
- src/topp-meny/topp-meny.css
- Aria-label og -labelledby er obligatorisk på modalar
- Import-mønster har endra seg
- Ikon i feilmelding ser ikkje ut til å vere innebygd meir, så eg fjernar det sidan det var noko nytt eg la til i feilmeldingane i dag.
- Brukar oppdaterte css-variablar
> Oppdater @navikt frå v5.18.3 til v6.0.0

- src/enhetsportefolje/enhet-kolonner.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/utils/enslig-forsorger.ts
- src/utils/utils.test.js
- src/utils/utils.ts
Verdi:
- lettare å sjå kva vi gjer med dataa vi får frå backend
- lettare kan dele denne koden med samarbeidspartnarar, sidan vi slepp referere til enkeltfunksjonar i ei diger fil
> Trekk ut hjelpefunksjonar for enslig forsørger til eiga fil

- src/components/fargekategori/FargekategoriFeilhandtering.tsx
- src/ducks/systemmeldinger.ts
- src/hooks/redux/use-systemmeldinger.tsx
- src/model-interfaces.ts
- Legg til (midlertidige) kommentarar for bruksområda til dei ulike typane i fila
- Flyttar ut typar som berre er brukt éin stad
- Brukar same Status-type over alt slik at vi slepp ha to typar med same innhald (ein const og ein enum).
> Trekk ut dei ulike domenemodellane til eigne filer

- src/components/tabell/arbeidslisteikon.tsx
- src/model-interfaces.ts
- src/typer/arbeidsliste.ts
- src/typer/filtervalg-modell.ts
- Fjern gamal og ubrukt type
- Flytt arbeidslistetypane til ei eiga fil, så det vert enno litt tydelegare at desse burde slettast.
- Legg til kommentarar på kvifor arbeidslistetypane ikkje er sletta, så eg slepp leite det fram kvar gong eg snublar over dei og tenker "burde ikkje desse vore sletta no?"
> Flytt arbeidslistetypar til eiga fil

- src/components/modal/tildel-veileder/tildel-veileder-renderer.tsx
- src/components/tabell/veiledernavn.tsx
- src/components/veileder-checkbox-liste/veileder-checkbox-liste.tsx
- src/ducks/innlogget-veileder.ts
- src/ducks/lagret-filter.ts
- src/ducks/veiledere.ts
- src/enhetsportefolje/enhet-brukerpanel.tsx
- src/enhetsportefolje/enhet-kolonner.tsx
- src/filtrering/filtrering-label-container.tsx
- src/hooks/redux/use-innlogget-ident.tsx
- src/middleware/api.ts
- src/mocks/data/innloggetVeileder.ts
- src/mocks/data/veiledere.ts
- src/model-interfaces.ts
- src/typer/enhet-og-veiledere-modeller.ts
- src/utils/metrikker/browser-metrikker.ts
- src/utils/metrikker/side-visning-metrikker.ts
- src/veilederoversikt/veilederoversikt-sidevisning.tsx
Flytt typar for veileder og enhet til eiga fil slik at det er lettare å sjå at desse heng saman, og ikkje har noko med dei andre typane i model-interfaces å gjere
> Flytt typar for veileder og enhet til eiga fil

- src/components/barinput/barinput-radio.tsx
- src/filtrering/filtrering-status/filtrering-status.tsx
Propen `filterNavn` vart brukt til to ting:
- Som postfiks i test-id
- Som key for react-elementet
Endring:
- Hardkode test-id.
- Fjern ubrukte test-id'ar.
- Bruke `value` til key i staden for filterNavn slik at vi kan fjerne heile filternavn-propen.
- Rydd litt i rekkefølgja på props i radioknapp-komponenten.
- Endre namn på prop `antall` til `statustall`, sidan det er det vi kallar talet i daglegtale.
Fordel:
- Lettare å finne bruken av test-id'ane
- Eit ledd i å gjere det tydelegare kva "filterNavn"-propen gjer for noko, og at den ikkje har noko med Filtermodellen å gjere
> Gjer props for statusfilter-radioknappar litt tydelegare

- src/mocks/data/portefolje.ts
- src/typer/bruker-modell.ts
Vi har felt som vert sendt til frontend, men som frontenden ikkje brukar. Det gjer at vi sender og tilgjengeleggjer meir data enn vi burde.
https://trello.com/c/ediXhBkP/1190-veilarbportefoljeflatefs-fjerne-kj%C3%B8nn-f%C3%B8dselsdato-og-dag-i-mnd-fr%C3%A5-frontend-objektet-dei-er-ikkje-brukt?filter=*
> Fjern ubrukte felt på brukarmodellen

- cypress/e2e/mine-filter_spec.ts
Ved å unngå å skrive inn ein tekst på 256 teikn eit teikn om gongen, med 10 millisekund venting mellom kvart teikn.
I staden: Lim inn tekst, legg til eit ekstra utropsteikn, fortel inputboksen at det har skjedd endringar, prøv å lagre.
Før:
Etter:
> Gjer cypress-test raskare
