navikt/veilarbportefoljeflatefs

- src/components/endringslogg/endringslogg-custom.tsx
- src/components/tour-modal/tour-modal-custom/tour-modal-custom.tsx
- src/components/tour-modal/tour-modal.less
Endringer i tekst for nytt filter og en liten endring i styling.
> Stepper endringslogg

- src/components/barinput/barinput-checkbox.tsx
- src/components/barinput/barinput.tsx
- src/components/barinput/barlabel.tsx
- src/components/tabell/etiketter.tsx
- src/components/tabelletiketter/tabelletiketter.less
- src/ducks/statustall.ts
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-status/filter-utils.ts
- src/filtrering/filtrering-status/filtrering-status-components/behov-og-arbeidsevnevurdering.tsx
- src/filtrering/filtrering-status/filtrering-status-components/ikke-permitterte-brukere.tsx
- src/filtrering/filtrering-status/filtrering-status-components/permitterte-brukere.tsx
- src/filtrering/filtrering-status/filtrering-status.tsx
- src/mocks/index.ts
- src/mocks/statustall.ts
- src/model-interfaces.ts
> Permittert filter

- src/ducks/features.ts
- src/konstanter.ts
- src/middleware/api.ts
- src/mocks/features.ts
- src/mocks/index.ts
- src/providers/initial-data-provider.tsx
**Hva?**
Henter ut vedtakstøtte featuretoggle fra nytt API
> endre feature url for vedtakstotte

- src/components/tabell-overskrift.tsx
- src/components/toolbar/paginering/paginering.tsx
- src/ducks/features.ts
- src/ducks/portefolje.ts
- src/ducks/utils.ts
- src/middleware/api.ts
- src/mocks/index.ts
- src/providers/initial-data-provider.tsx
**Hva?**
- Lagt til enhetsId i kall for å hente ut vedtaksstotte featuretoggle for gitt enhet
- Håndtere feil fra portefolje API
> Tc-304 Legg til enhetsId for vedtaksstotteFeature

- src/ducks/portefolje.ts
- src/mocks/index.ts
- src/utils/utils.tsx
**Hva?**
For å gå vekk fra deprecated bibliotek kapitalisering på backend gjøres heller dette i frontend.
> TC-291 kapitaliser navn

- cypress/integration/diverse_spec.js
- src/components/dropdown/dropdown.tsx
- src/components/endringslogg/endringslogg-innhold.tsx
- src/components/endringslogg/endringslogg-tour-wrapper.tsx
- src/components/endringslogg/endringslogg.tsx
- src/components/endringslogg/utils/endringslogg-custom.tsx
- src/components/modal/feilmelding-tildeling-modal.tsx
- src/components/til-toppen-knapp/til-toppen-knapp.tsx
- src/components/tilbakemelding/tilbakemelding-fab.tsx
- src/components/toolbar/toolbar-knapp.tsx
- src/components/veileder-checkbox-liste/veileder-checkbox-liste.tsx
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/filtrering/filtrering-label-container.tsx
- src/filtrering/filtrering-veiledere.tsx
- src/hooks/portefolje/use-veileder-har-portefolje.tsx
- src/hooks/use-outside-click.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/utils/dato-utils.ts
- src/utils/frontend-logger.ts
- src/veiledere/veilederside-visning.tsx
Reverts navikt/veilarbportefoljeflatefs#494
> Revert "kz-0 rydding i kode"

- src/components/endringslogg/utils/endringslogg-custom.tsx
**Hva?**
Legg til ny endringsloggmelding
> TC-339 legg til endringslogg

- src/components/tilbakemelding/tilbakemelding-modal.tsx
> Legg til komma i tekst

- .github/workflows/build-deploy.yaml
- README.md
- src/components/alertstripe-tekniske-problemer.tsx
- src/components/modal/feilmelding-tildeling-modal.tsx
- src/mocks/features.ts
Oppdater infotekst og refaktorer alertstripe
> Oppdater infotekst i vedlikeholds-alert

- .github/workflows/build-deploy-feature-branch-q1.yaml
- Dockerfile
- README.md
- nais-dev.yaml
\+ Ny workflow for deploy til Q1
> TC-20 dobbelt API-kall bugfix

- src/ducks/portefolje.ts
> Bugfix statustall etter tildeling av veileder

- src/components/toggle/dark-mode-toggle.less
- src/components/toggle/dark-mode-toggle.tsx
**Hva?**
- Bruk ny toggle/switch for darkmode 🌚 
https://gyazo.com/40830bb7bb53c50798ff342a7e8f2d79
> TC-122 bytt til navdesign toggle

- src/components/barinput/barlabel.tsx
**Hva?**
- Bruk `switch` fra navdesign til darkmode toggle 🌔
> Darkmode toggle

- src/minoversikt/minoversikt-arbeidslistepanel.tsx
når det fins brukere med diskresjonskode 7
> Tc-131 Fiks veileders arbeidsliste åpnes ikke 

- src/minoversikt/minoversikt-arbeidslistepanel.tsx
åpnes ikke når det fins brukere med diskresjonskode 7
> Tc-131 Fiks veileders arbeidsliste 

- src/components/barinput/barlabel.tsx
- src/components/til-toppen-knapp/til-toppen-knapp.less
Gjør knappen lik den i detaljer
> Fiks på til-toppen-knappen

- src/style.less
**Hva?**
- Fiks slik at sort bakrunn ikke blir borte ved scroll ⚫️
> TC-00 fiks darkmode bakrunn

- cypress/integration/arbeidsliste_spec.js
- src/components/modal/arbeidsliste/arbeidsliste.less
- src/components/modal/arbeidsliste/fjern-fra-arbeidsliste-form.tsx
- src/components/modal/arbeidsliste/legg-til-arbeidslisteform.tsx
- src/components/toolbar/listevisning/listevisning-utils.ts
- src/ducks/statustall.ts
- src/ducks/ui/listevisning-selectors.ts
- src/ducks/ui/listevisning.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-status/filtrering-status.tsx
- src/hooks/portefolje/use-fetch-portefolje.tsx
- src/middleware/api.ts
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/minoversikt/minoversikt-side.tsx
- src/minoversikt/motekalender/motekalender.less
- src/minoversikt/motekalender/motekalender.tsx
- src/minoversikt/motekalender/motekollonne.tsx
- src/minoversikt/motekalender/motetabell.tsx
- src/mocks/features.ts
- src/mocks/index.ts
- src/mocks/portefolje.ts
- src/mocks/statustall.ts
- src/model-interfaces.ts
- src/utils/dato-utils.ts
**Hva**
- fetch `statustall` når man legger til eller fjerner brukere fra arbeidslista 🐊
> Tc 102 oppdater statustall bug

- src/minoversikt/motekalender/motekollonne.tsx
- src/mocks/portefolje.ts
+ Legger på fornavn på deltakere i møteplanen
> Håndterer skjermede brukere

- src/components/modal/arbeidsliste/fjern-fra-arbeidsliste-form.tsx
- src/components/modal/arbeidsliste/legg-til-arbeidslisteform.tsx
Reverts navikt/veilarbportefoljeflatefs#625
> Revert "Tc 102 oppdater statustall bug"

- cypress/integration/arbeidsliste_spec.js
- src/mocks/portefolje.ts
**Hva?**
- Fiks feilende tester dersom `hentArbeidslisteForBruker` ikke returnerer arbeidsliste
> arbeidsliste test

- .nais/obo-nais-dev.yaml
- src/components/toolbar/listevisning/listevisning-utils.ts
- src/ducks/filtrering.ts
- src/ducks/portefolje.ts
- src/ducks/ui/listevisning-selectors.ts
- src/ducks/ui/listevisning.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filterform/checkbox-filterform.tsx
- src/filtrering/filtrering-filter/filtrering-filter.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/minoversikt/moteplan/motekollonne.tsx
- src/mocks/portefolje.ts
- src/model-interfaces.ts
- src/utils/dato-utils.ts
- src/utils/utils.tsx
> Tc 169  foedeland filter

- .github/workflows/poao-frontend-container-prod.yaml
- src/components/tabell/brukernavn.tsx
- src/components/tabell/sisteendringkategori.tsx
- src/minoversikt/moteplan/motekollonne.tsx
- src/utils/url-utils.ts
Bruker parameter #visAktivitetsplanen for å kunne lenke direkte til aktivitetsplanen.
Dette overskriver historikken som gjør at f.eks. detaljer er "sticky" hvis man har vært inne der under et tidligere besøk til veilarbperson
> bruker: #visAktivitetsplanen

- .nais/obo-nais-dev.yaml
> wonderwall.nais.io/beta

- .husky/pre-commit
- .huskyrc
- package-lock.json
- package.json
Forklaring:
* `"prepare": "husky install"` i `package.json`: installer husky når `npm install` kjøres
* `husky install`: konfigurer git hooks til å peke på ./husky
> Kjør lint-staged på pre-commit vha. husky

- src/components/toolbar/listevisning/listevisning-utils.ts
- src/ducks/ui/listevisning-selectors.ts
- src/ducks/ui/listevisning.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filtrering-filter.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/mocks/portefolje.ts
- src/model-interfaces.ts
Oppretta to kolonner som skal dukke opp når man trykker på "CV kan deles status". Alt dette ligger bak en featuretoggle, så tekstene og om vi skal ha begge kolonnene er ikke sikkert (den ene kolonnen sier bare alltid "JA", så vet ikke helt hvor verdifull den er...). Men jeg oppretter PR-en for jeg tenker det er fint å ta ut små deler, siden det uansett ikke (SKAL) påvirke noe annet iom at det ligger under en featuretoggle.
> Stilling fra nav Lage kolonner for filteret i oversikten

- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filtrering-filter.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/model-interfaces.ts
Flyttet Kolonnen for CV svarfrist bakerst. Endret litt på tekst i dropdown, fjernet info i-en siden Stilling fra NAV ikke er avtalt med NAV og flyttet stilling fra NAV nederst i "Aktivitet"
> Endring i tekst og plassering av Stilling fra NAV

- .nais/obo-nais-dev.yaml
- .nais/obo-nais-prod.yaml
Ref: https://nav-it.slack.com/archives/CQ2H1AY3Z/p1673598233489549
> TC-272 Bumpe poao-frontend til siste versjon

- src/components/formik/formik-input.tsx
- src/components/modal/arbeidsliste/arbeidsliste-form.tsx
- src/components/modal/arbeidsliste/arbeidsliste.css
- src/components/modal/arbeidsliste/rediger-arbeidsliste-form.tsx
- src/components/modal/mine-filter/mine-filter.css
- src/components/modal/modal.css
- src/components/modal/varselmodal/varsel-modal.css
Gjør sånn at små modaler ikke har full bredde, og legger til bittelitt mellomrom mellom delene av varselmodalen
> Justering av modalbredde

- .github/workflows/pull-request.yaml
- package-lock.json
- src/components/dropdown/dropdown.tsx
- src/components/knapper/legg-til-knapp.tsx
- src/components/modal/arbeidsliste/rediger-arbeidsliste-form.tsx
- src/components/tabell/sortering-header.tsx
- src/components/tabell/tabell.css
- src/components/toolbar/legg-til-arbeidsliste-knapp.tsx
- src/components/toolbar/toolbar-knapp.tsx
- src/components/toolbar/toolbar.css
- src/components/toolbar/velg-kolonner.tsx
- src/style.css
- src/tabell.css
- src/veiledere/veiledere-tabell.tsx
Fjerner overflødige BodyShort og rydder litt i CSS.
Baserer seg på #781
> Rydde litt i knapper

- public/internarbeidsflatedecorator/v2.1/static/css/main.css
- src/components/modal-liste.css
- src/components/modal/arbeidsliste/arbeidsliste-modal-rediger.tsx
- src/components/modal/arbeidsliste/arbeidsliste-modal.tsx
- src/components/modal/egenModal.tsx
- src/components/modal/mine-filter/mine-filter.css
- src/components/modal/varselmodal/varsel-modal.css
- src/components/modal/varselmodal/varselmodal.tsx
- Legger på <Modal.Content>-komponenten der den mangler
- Justerer litt på innholdet i varsel-modal
- Kommenterer ut litt CSS som kommer med internarbeidsflatedecorator som jeg ikke kan skjønne hva gjør der (annet enn å gjøre at ting ser annerledes ut lokalt) fordi den komponenten bruker ikke det nye designsystemet
> Bugfix modalpadding

- .github/workflows/deploy-dev-gcp.yaml
- cypress/support/commands.js
- src/components/til-toppen-knapp/til-toppen-knapp.css
- src/components/til-toppen-knapp/til-toppen-knapp.tsx
- src/components/toolbar/toolbar.css
- src/components/toolbar/toolbar.tsx
- src/enhetsportefolje/brukerliste.css
- src/enhetsportefolje/enhet-side.tsx
- src/enhetsportefolje/enhetsportefolje.css
- src/filtrering/filtrering-label.css
- src/minoversikt/minoversikt-side.tsx
- src/style.css
* Rydder opp i "sticky skygge"
* Fikser hjørnene i brukerliste, så de ikke er hullete ([se bilde av før-tilstand på Trello](https://trello.com/c/kM4qFCsZ/348-fikse-hull-i-hj%C3%B8rnene-p%C3%A5-brukerlisten-i-oversikten))
> TC-348 Bugfiks: hjørner på brukerliste

- package-lock.json
- package.json
- src/components/toolbar/listevisning/listevisning-utils.ts
- src/ducks/ui/listevisning-selectors.ts
- src/ducks/ui/listevisning.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/filtrering/filter-konstanter.ts
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/mocks/portefolje.ts
- src/model-interfaces.ts
- src/utils/utils.tsx
Reverts navikt/veilarbportefoljeflatefs#831
Ser noen ting i dataene vi ikke kan forklare helt, ruller tilbake.
> Revert "Legg til kolonne for vurderingsfrist for AAP"

- src/index.tsx
This reverts commit ddee41e343ada48531560af0d1a66b7a703c9c20.
> Revert "TC-386 Ta i bruk rapportering av unhandled exceptions"

- .github/workflows/deploy-dev-gcp.yaml
* Alltid kjøre tester ved pull request
* Ikke deploye ved pull request
* Alltid deploye ved manuell dispatch
Måtte splitte opp i to "jobs" for å kunne separere use-casene
> Tilpasse dev deployment workflow

- src/components/aksjon-knapp-med-popover-feilmelding/aksjon-knapp-med-popover-feilmelding.tsx
- src/components/tabell/brukernavn.tsx
- src/components/tabell/sisteendringkategori.tsx
- src/minoversikt/moteplan/motekollonne.tsx
Skal vi ha featuretoggle på denne? Hvis ikke, fjern den fra unleash og hele koden.
> Ctrlklikk på navn åpner ny fane

- src/components/toolbar/listevisning/listevisning-utils.ts
- src/ducks/ui/listevisning-selectors.ts
- src/ducks/ui/listevisning.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filtrering-filter.tsx
- src/filtrering/filtrering-label-container.tsx
- src/konstanter.ts
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/mocks/portefolje.ts
- src/model-interfaces.ts
Med mulighet for endring av situasjon er det også nå kommet inn flere mulige situasjoner som må representeres i filteret.
> Lagt til flere alternativ for filter situasjon

- .github/workflows/deploy-dev-gcp.yaml
- .github/workflows/depoloy-prod-gcp.yaml
- .github/workflows/poao-frontend-container-dev.yaml
- .github/workflows/poao-frontend-container-prod.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/update-github-pages.yaml
Reverts navikt/veilarbportefoljeflatefs#886
> Revert "oppdatere til node 20"

- .github/workflows/deploy-dev-gcp.yaml
- .github/workflows/depoloy-prod-gcp.yaml
- .github/workflows/poao-frontend-container-dev.yaml
- .github/workflows/poao-frontend-container-prod.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/update-github-pages.yaml
Reverts navikt/veilarbportefoljeflatefs#888
> Revert "Revert "oppdatere til node 20""

- .github/workflows/deploy-dev-gcp.yaml
- .github/workflows/depoloy-prod-gcp.yaml
- .github/workflows/poao-frontend-container-dev.yaml
- .github/workflows/poao-frontend-container-prod.yaml
- .github/workflows/pull-request.yaml
- .github/workflows/update-github-pages.yaml
- package-lock.json
- package.json
- src/amplitude/amplitude.ts
Reverts navikt/veilarbportefoljeflatefs#890
Dette hadde ingen dessverre ingen effekt, så legger det tilbake.
> Revert "Ta vekk amplitude og node20 for å se om det har effekt på econnresetfeil"

- src/components/modal/arbeidsliste/arbeidsliste-informasjonsmelding.tsx
> Ny/oppdatert tekst i alerten i arbeidslisten angående retningslinjer

- src/components/sidebar/mine-filter-tab.tsx
- src/filtrering/filtrering-mine-filter/drag-and-drop/drag-and-drop-row.tsx
- src/filtrering/filtrering-mine-filter/drag-and-drop/mouse-drag-event-listeners.tsx
Kari ønsket litt data på "endre rekkefølge" på mine filter så har satt opp amplitudemålinger på dette.
> tracking på mine filter (endring av rekkefølge)

- src/mocks/data/portefolje.ts
- src/model-interfaces.ts
Typesikrar mockdata for møteplan og overgangsstønad for einslege forsørgarar.
> Rydd i mockdata

- cypress/e2e/arbeidsliste_spec.js
- cypress/e2e/arbeidslistestatus_spec.js
- cypress/support/commands.js
- src/components/modal/arbeidsliste/arbeidsliste-modal-rediger.tsx
- src/components/modal/arbeidsliste/arbeidsliste-modal.tsx
- src/minoversikt/minoversikt-arbeidslistepanel.tsx
- src/minoversikt/minoversikt-bruker-panel.tsx
- src/mocks/api/veilarbportefolje.ts
- src/mocks/data/portefolje.ts
Slik at vi forhåpentlegvis får færre ting som knekk når vi går til @navikt/ds v5
> Rydd i cypress-testar del 1

- cypress/e2e/arbeidsliste_spec.js
- cypress/e2e/arbeidslistestatus_spec.js
- package-lock.json
- package.json
- src/components/endringslogg/modal/tour-modal/tour-modal.tsx
- src/components/modal/arbeidsliste/arbeidsliste-modal-rediger.tsx
- src/components/modal/arbeidsliste/arbeidsliste-modal.tsx
- src/components/modal/egenModal.tsx
- src/components/modal/lastermodal/laster-modal.tsx
- src/components/modal/tildel-veileder/tildel-veileder.tsx
- src/components/modal/varselmodal/varselmodal.tsx
- src/components/modal/veiledergruppe/veiledergruppe-modal.tsx
- src/minoversikt/huskelapp/HuskelappIkonInngang.tsx
- src/minoversikt/huskelapp/LagEllerEndreHuskelappModal.tsx
Og skru på at ein kan lukke modalar ved å klikke utanfor dei
> Oppdater designsystemet til versjon 5.8

- cypress/support/e2e.js
- package-lock.json
- package.json
Denne hadde ein sub-dependency til ein usikker postcss-klasse
> Avinstaller ubrukt dependency: 'cypress-dark'

- src/components/modal/feilmelding-brukere-modal.tsx
- src/components/modal/filter-feil-modal.tsx
- src/components/modal/veiledergruppe/ulagrede-endringer-modal.tsx
for å få bygg til prod til å gå gjennom
> Fjern ubrukte importar

- src/filtrering/filtrering-mine-filter/mine-filter_innhold.tsx
Alert hvis veileder har brukt MIN_ARBEIDSLISTE i Mine filter
> Info alert mine filter

- src/enhetsportefolje/brukerliste.css
- src/enhetsportefolje/enhet-brukerpanel.tsx
- src/minoversikt/huskelapp/HuskelappIkonInngang.tsx
- src/minoversikt/huskelapp/LagHuskelappInngang.tsx
- src/minoversikt/huskelapp/huskelapp-wrapper/huskelapp-postitstyling.css
- src/minoversikt/huskelapp/huskelapp.css
- src/minoversikt/huskelapp/modalvisning/HuskelappForModal.tsx
- src/minoversikt/huskelapp/modalvisning/HuskelappModal.tsx
- src/minoversikt/huskelapp/modalvisning/SlettHuskelappKnapp.tsx
- src/minoversikt/huskelapp/modalvisning/modalvisning.css
- src/minoversikt/huskelapp/panelvisning/HuskelappForPanel.tsx
- src/minoversikt/huskelapp/panelvisning/HuskelappPanelvisning.tsx
- src/minoversikt/huskelapp/panelvisning/panelvisning.css
- src/minoversikt/huskelapp/redigering/GammelArbeidsliste.tsx
- src/minoversikt/huskelapp/redigering/HuskelappInfoAlert.tsx
- src/minoversikt/huskelapp/redigering/NyHuskelapp.tsx
- src/minoversikt/huskelapp/redigering/RedigerHuskelappModal.tsx
- src/minoversikt/huskelapp/redigering/SlettArbeidsliste.tsx
- src/minoversikt/huskelapp/redigering/rediger-huskelapp.css
- src/minoversikt/minoversikt-bruker-panel.tsx
- src/minoversikt/minoversikt.css
- src/mocks/api/veilarbportefolje.ts
- src/style.css
Slik at ting vert likare i oversikten og visittkortet.
> Tek i bruk det nye designet for migreringsmodal

- src/minoversikt/huskelapp/modalvisning/modalvisning.css
- src/minoversikt/huskelapp/panelvisning/panelvisning.css
- src/minoversikt/huskelapp/redigering/rediger-huskelapp.css
for å få bygg til å gå gjennom
> Bruker flex-end i staden for end i styling

- src/filtrering/filtrering-mine-filter/mine-filter_innhold.tsx
- src/filtrering/filtrering-status/arbeidsliste.css
- src/filtrering/filtrering-status/arbeidsliste.tsx
- src/minoversikt/huskelapp/modalvisning/SlettHuskelappKnapp.tsx
- src/minoversikt/huskelapp/redigering/HuskelappInfoAlert.tsx
- src/minoversikt/huskelapp/redigering/RedigerHuskelappModal.tsx
> Tekstendringer

- src/minoversikt/huskelapp/redigering/RedigerHuskelappModal.tsx
medan vi manglar avbryt-bekrefting
> Ta bort overlay-click for redigeringsmodal

- src/components/fargekategori/FargekategoriFeilhandtering.tsx
slik at bygget bygg og deploy deployar
> Bruk rett mengd =-teikn

- .prettierignore
- src/minoversikt/huskelapp/HuskelappIkonInngang.tsx
- src/minoversikt/huskelapp/panelvisning/HuskelappPanelvisning.tsx
- src/minoversikt/huskelapp/redigering/HuskelappModal.tsx
- src/minoversikt/huskelapp/redigering/NyHuskelapp.tsx
- src/mocks/data/portefolje.ts
- tsconfig.json
Vi sjekker om Formik-skjemaet er "dirty" og ber om bekreftelse på lukking
> Bekreft lukking når ulagra innhold i huskelappmodal

- .github/workflows/pull-request.yaml
slik at vi unngår at bygg feiler på linting først når vi merger til main
> Legg til byggesteg for kode i PR-ar

- cypress/e2e/diverse_spec.js
- src/filtrering/filter-konstanter.ts
Vi prøver å fikse backenden så det skal funke uten Ø!
> Revert "Fikser bad request mot backend for filter overgangsstønad"

- src/components/arbeidsliste/SlettArbeidslisteKnapp.tsx
- src/components/toolbar/toolbar-knapp.tsx
- src/enhetsportefolje/brukerliste.css
- src/minoversikt/minoversikt-arbeidslistepanel.tsx
Gjenbruker KnappMedBekreftHandling.
> Legger til sletteknapp direkte i arbeidslistepanel. 

- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/model-interfaces.ts
https://trello.com/c/flmdYUVI/696-gjere-det-mogleg-%C3%A5-sortere-p%C3%A5-fleire-kolonner
> Leggje til sortering på kolonner for tiltakshendelse

- src/components/tabell/kolonner/lenkekolonne.tsx
- src/enhetsportefolje/enhet-kolonner.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/mocks/data/portefolje.ts
Lokalt er det helt random hvilke(n) test(er) som feiler..
> Fullfør refaktorering av lenkekolonne

- cypress/e2e/filter_spec.js
- src/enhetsportefolje/brukerliste.css
- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-bruker-panel.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/minoversikt/minoversikt.css
Dette er steg éin av veldig mange steg for å få tabellen til å bli lettare å style fint.
> Refaktorer styling oversikttabell

- src/mocks/api/veilarbportefoljeflatefs.ts
- src/mocks/data/mockfeatures.ts
> Gje mock-features eit meir skildrande namn

- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/mocks/data/portefolje.ts
- src/style.css
Gjev meir plass til tiltakshendelse-lenke og bryt lange ord i to om naudsynt
> Gjev meir plass til tiltakshendelse-lenke

- src/components/arbeidsliste/SlettArbeidslisteKnapp.tsx
- src/middleware/api.ts
- src/minoversikt/huskelapp/HuskelappIkonInngang.tsx
- src/minoversikt/huskelapp/LagHuskelappInngang.tsx
- src/minoversikt/huskelapp/redigering/HuskelappModal.tsx
- src/minoversikt/huskelapp/redigering/lagreHuskelapp.ts
- src/minoversikt/huskelapp/redigering/slettEksisterendeArbeidsliste.ts
- Ikkje send inn arbeidslister til huskelapp-modalane
- Ikkje utfør sletting av arbeidslister, til dømes ved oppretting av huskelapp.
> Ikkje vis migreringsmodal eller slett arbeidslister når feature-toggle er på

- src/utils/url-utils.ts
Pass på at dette blir riktig! Ansatt-ingresser skal bare gjelde dev-miljø.
> Riktig url til personflate når veileder bruker ansatt-ingress

- src/components/modal/tildel-veileder/tildel-veileder-utils.ts
- src/components/modal/tildel-veileder/tildelveileder.test.ts
Prodfeil der ein ikkje får tildelt veiledarar på tvers av kontor
> Prøv å reversere fiks for å sjå om den er årsaken til prodfeil

- .github/workflows/pull-request.yaml
- src/components/modal/tildel-veileder/tildel-veileder-utils.ts
- src/components/modal/tildel-veileder/tildelveileder.test.ts
Reverserer https://github.com/navikt/veilarbportefoljeflatefs/pull/1112
som reverserte delar av https://github.com/navikt/veilarbportefoljeflatefs/pull/1106
> Skru på igjen fiks vi tok bort under feilsøking

- src/components/modal/tildel-veileder/tildel-veileder.tsx
- src/components/toolbar/toolbar.tsx
- src/ducks/ui/listevisning-selectors.ts
- src/filtrering/filtrering-status/arbeidsliste.css
- src/filtrering/filtrering-status/arbeidsliste.tsx
- src/filtrering/filtrering-status/filtrering-status.tsx
- src/minoversikt/huskelapp/redigering/HuskelappInfoAlert.tsx
- src/minoversikt/minoversikt-bruker-panel.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- Ikkje nevn arbeidslister i åtvaring ved tildeling av veileder
- Skjul filter for arbeidsliste
- Ikkje vis "Vi sletter snart arbeidslister"-melding når arbeidslister er skrudd av
- Info om personvern i huskelapp-skriving
- Skjul kolonner for arbeidsliste i tabell
- Skjul kolonner for arbeidsliste i Velg kolonner
> Skjul filter for arbeidsliste

- src/components/barinput/bar.css
- src/filtrering/filtrering-status/filtrering-status.tsx
Bruk semantisk skillelinje-farge mellom filterbolkar 
(og skriv om klassenamn til å ikkje bruke camelCase)
> Bruk semantisk skillelinje-farge mellom filterbolkar

- src/filtrering/filtrering-filter/filtrering-filter.tsx
> Endre test på filter for svar fra registreringen (presisere arb.søkerregisteret)

- src/ducks/filtrering.ts
- src/ducks/ui/listevisning-selectors.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filtrering-filter.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/mocks/data/portefolje.ts
- src/model-interfaces.ts
Legg til rette for å filtrere på innsatsgruppe for gjeldende § 14 a-vedtak. 
(Sjølve filtreringa fungerer ikkje før backend og så har fått endringa. Endringa er bak feature-toggle.)
> Legg til filter for innsatsgruppe gjeldende § 14 a-vedtak

- src/ducks/filtrering.ts
- src/ducks/ui/listevisning-selectors.ts
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filtrering-filter.tsx
- src/model-interfaces.ts
Legg til filter for å vise brukarar med dei ulike hovedmåla på gjeldande § 14 a-vedtak.
> Legg til hovedmål-filter for gjeldende § 14 a-vedtak

- src/components/tabell/headerceller/BarnUnder18Ar.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/filtrering/filter-konstanter.ts
- src/minoversikt/minoversikt-listehode.tsx
- src/model-interfaces.ts
Rydd i enum for sorteringsfelt så den reflekterer endringar i backend sin enum.
Stort sett handlar det om å rette skrivefeil i namn på ting.
> Rydd i enum for sorteringsfelt

- src/components/tabell/kolonner/lenkekolonne.tsx
- src/enhetsportefolje/enhet-kolonner.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/minoversikt-listehode.tsx
- src/mocks/data/portefolje.ts
- src/model-interfaces.ts
- Opprett mock-data
- Vis data for utgåtte varsel i tabell i oversikten
- Håndter at lenkekolonner kan innehalde lenker med absolutt url
> Vis data for utgåtte varsel

- src/components/tabell/headerceller/FilterhendelseDatoOpprettet.tsx
- src/model-interfaces.ts
Legg til sortering på filterhendelsesdato-kolonna.
Syster-PR:
https://github.com/navikt/veilarbportefolje/pull/1814
> Legg til sortering på datokolonna for hendelsesfiltera

- README.md
- cypress/e2e/filter_spec.js
- src/components/tabell/headerceller/Motestatus.tsx
- src/components/tabell/headerceller/VenterPaSvarFraNav.tsx
- src/components/tabell/headerceller/enhetens-oversikt/VeilederNavident.tsx
- src/components/tilbakemelding/tilbakemelding-modal.tsx
- src/components/toolbar/velg-kolonner/velg-kolonner-config.ts
- src/enhetsportefolje/enhet-kolonner.tsx
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filtrering-filter.tsx
- src/filtrering/filtrering-status/filtrering-status.tsx
- src/filtrering/filtrering-veiledere.tsx
- src/minoversikt/minoversikt-kolonner.tsx
- src/minoversikt/moteplan/motekollonne.tsx
- src/minoversikt/moteplan/motetabell.tsx
- src/mocks/data/endringslogg.ts
- src/mocks/data/innloggetVeileder.ts
- src/mocks/data/tiltak.ts
- src/mocks/data/veiledere.ts
- src/veiledere/veiledere-tabell.tsx
Trello-oppgåve: https://trello.com/c/4VtXJPhJ/680-bytte-fr%C3%A5-nav-til-nav
Kort fortalt: Nav har bestemt at dei heiter Nav, ikkje NAV. Det skal reflekterast i løysingane også.
> Bytt frå NAV til Nav i tekstar

- src/innholdslaster/get-feilmelding-for-reducer.tsx
Heller be brukaren melde i frå i Porten om problemet varer over tid.
> Ta bort "vi jobber å løse disse" frå feilmelding

- src/amplitude/filter-malinger.ts
Har sjekket Amplitude i dev, og sidenavn tilsvarer Enhetens oversikt / Min oversikt.
> Legger til sidenavn på Amplitude-målinger

- src/ducks/filtrering.ts
- src/ducks/ui/listevisning-selectors.ts
- src/filtrering/filter-konstanter.ts
- src/filtrering/filtrering-filter/filterform/aktiviteter-filterform/aktivitet-filterform-controller.tsx
- src/typer/filtervalg-modell.ts
Samlar typar og relevante konstantar for Aktiviteter-filter på same stad.
> Rydd i Aktiviteter-filtervalg

- src/components/endringslogg/endringslogg-container.tsx
- src/components/endringslogg/endringslogg.css
- src/components/endringslogg/endringslogg.tsx
- src/components/endringslogg/icons/endringslogg-icon.tsx
- src/components/endringslogg/transition-container.tsx
- src/topp-meny/topp-meny.tsx
Mål: Ta bort kode som ikkje vert brukt, reduser kompleksitet i komponentane. Gjer det lettare å forstå kva som faktisk vert vist når vi bruker komponenten.
> Gjer endringslogg-komponenten litt mindre kompleks

- src/components/tabell/headerceller/Status14aVedtak.tsx
- src/enhetsportefolje/enhet-listehode.tsx
- src/minoversikt/minoversikt-listehode.tsx
> Rett skrivefeil i komponentnamn

- src/components/tabell/innholdsceller/Fodeland.tsx
- src/components/tabell/innholdsceller/enhetens-oversikt/veilederNavident.tsx
- src/enhetsportefolje/enhet-kolonner.tsx
- src/minoversikt/minoversikt-kolonner.tsx
Bruk same namn på innhald- og headerceller, slik at ein lettare ser kva som høyrer saman.
Flytt visningslogikk ut av const slik at det går raskare å samanlikne visning av innhald- og headerceller.
> Rydd litt meir i innhaldsceller

- src/filtrering/filtrering-mine-filter/mine-filter_innhold.css
- src/filtrering/filtrering-mine-filter/mine-filter_innhold.tsx
- src/mocks/data/mine-filter.ts
https://trello.com/c/czJz2Xqg/1195-veilarbportefoljeflatefs-oppdater-alert-tekst-for-du-har-lagret-filter-med-arbeidsliste
> Oppdater infomelding om arbeidsliste i lagra filter

- cypress.config.ts
- package-lock.json
- package.json
- src/application.tsx
- src/hooks/portefolje/use-set-enhet-i-url.ts
- src/hooks/portefolje/use-sync-state-med-url.ts
- src/hooks/use-redirect-on-mount.ts
- src/minoversikt/minoversikt_wrapper.tsx
- src/model-interfaces.ts
- src/routing.tsx
- src/topp-meny/lenker.tsx
- src/veilederoversikt/veilederoversikt-tabellrad.tsx
Kjelder for migreringa:
https://reactrouter.com/6.30.1/upgrading/v5#refactor-custom-routes
https://github.com/remix-run/react-router/discussions/8753
https://gist.github.com/mjackson/b5748add2795ce7448a366ae8f8ae3bb
https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f
https://remix.run/blog/react-router-v6#upgrading-to-react-router-v6
Eg har testa løysinga i dev i lag med @Mathiamu.
> Oppdater React Router til versjon 6

- src/filtrering/filtrering-filter/filterform/checkbox-filterform.tsx
- src/filtrering/filtrering-filter/filtrering-filter.tsx
Verdi: Ein mindre kompleks komponent som det går raskare å setje seg inn i. Unngå å vedlikehalde ubrukt kode.
> Rydd i props for CheckboxFilterform

- package-lock.json
- package.json
- src/minoversikt/huskelapp/redigering/HuskelappModal.tsx
Eit mellomsteg på vegen mot versjon 7
> Oppdater designsystemet til versjon 6.17

- src/minoversikt/moteplan/vis-flere-moter-knapper.tsx
Logg klikk på Møteplan-knappar til Amplitude slik at vi kan sjå om begge blir brukt. Då kan vi på sikt vurdere om vi berre treng "Se alle", eller om det har verdi å ha både den og "Se flere møter"
> Logg klikk på Møteplan-knappar til Amplitude
